#!/usr/bin/env python3
"""Create bounded AI-draft learner text from externally reviewed selections.

The selections are authoritative; this script neither runs the heuristic nor
changes sourced facts.  Text is intentionally marked ai_draft for later review.
"""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SEL=ROOT/'data/learner-content-100-selection-reviewed.json'; FACTS=ROOT/'data/learner-content-100-review-input.json'; OUT=ROOT/'data/learner-content-100-draft.json'
def canon(x): return json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':'))
# key: short Chinese gloss, one sense-bound A1-B1 example, Chinese rendering.
TEXT={
'grand|ADJ':('大的；高的','La maison est grande.','这座房子很大。'),'petit|ADJ':('小的','Le sac est petit.','这个包很小。'),'bon|ADJ':('好的；好吃的','Ce gâteau est bon.','这个蛋糕很好吃。'),'nouveau|ADJ':('新的','J’ai un nouveau téléphone.','我有一部新手机。'),'jeune|ADJ':('年轻的','Elle est encore jeune.','她还很年轻。'),'seul|ADJ':('独自的；唯一的','Il vit seul.','他独自生活。'),'français|ADJ':('法国的；法语的','C’est un livre français.','这是一本法语书。'),'beau|ADJ':('美丽的；好看的','Le jardin est beau.','这个花园很美。'),'dernier|ADJ':('最后的；上一个的','C’est le dernier train.','这是最后一班火车。'),'sûr|ADJ':('确定的；可靠的','Tu es sûr de la réponse ?','你确定这个答案吗？'),'vieux|ADJ':('旧的；年老的','Cette voiture est vieille.','这辆车很旧。'),'vrai|ADJ':('真的；真实的','C’est vrai.','这是真的。'),
"aujourd'hui|ADV":('今天','Aujourd’hui, je travaille à la maison.','今天我在家工作。'),'près|ADV':('近；靠近','L’école est près d’ici.','学校离这里很近。'),'peut-être|ADV':('也许','Peut-être qu’il viendra demain.','他明天也许会来。'),'mieux|ADV':('更好地','Je comprends mieux maintenant.','我现在理解得更好了。'),'surtout|ADV':('尤其；特别','J’aime surtout le chocolat.','我尤其喜欢巧克力。'),'loin|ADV':('远','La gare est loin.','车站很远。'),"d'abord|ADV":('首先；起初','D’abord, lis la question.','首先，读一下问题。'),
'an|NOM':('年','Un an passe vite.','一年过得很快。'),'homme|NOM':('男人；成年男性','Cet homme attend le bus.','这位男士在等公交车。'),'jour|NOM':('日；一天','Quel jour sommes-nous ?','今天是星期几？'),'femme|NOM':('女人；成年女性','Cette femme est médecin.','这位女士是医生。'),'heure|NOM':('小时','Le cours dure une heure.','这门课持续一小时。'),'temps|NOM':('时间','Je n’ai pas le temps.','我没有时间。'),'monde|NOM':('世界','Le monde est grand.','世界很大。'),'vie|NOM':('一生；生命历程','Sa vie a beaucoup changé.','她的一生发生了很大变化。'),'enfant|NOM':('孩子','L’enfant joue dans le jardin.','孩子在花园里玩。'),'chose|NOM':('东西；事情','C’est une chose importante.','这是一件重要的事。'),'personne|NOM':('人','Il n’y a personne ici.','这里没有人。'),'année|NOM':('年','Cette année, je voyage moins.','今年我旅行得更少。'),'maison|NOM':('房子；家','Ils rentrent à la maison.','他们回家。'),'pays|NOM':('国家；地区','La France est un grand pays.','法国是一个大国。'),
'être|VER':('是；处于','Elle est contente.','她很高兴。'),'avoir|VER':('有','J’ai deux frères.','我有两个兄弟。'),'faire|VER':('做；进行','Je fais mes devoirs.','我在做作业。'),'aller|VER':('去','Nous allons au marché.','我们去市场。'),'dire|VER':('说；告诉','Il dit bonjour.','他打招呼。'),'pouvoir|VER':('能够；可以','Tu peux entrer.','你可以进来。'),'voir|VER':('看见；见到','Je vois la mer.','我看见大海。'),'vouloir|VER':('想要；愿意','Je veux un café.','我想要一杯咖啡。'),'savoir|VER':('知道；会','Elle sait nager.','她会游泳。'),'venir|VER':('来','Tu viens avec nous ?','你和我们一起来吗？'),'prendre|VER':('拿；乘坐','Je prends le train.','我坐火车。'),'devoir|VER':('必须；应该','Je dois partir maintenant.','我现在必须走了。'),'passer|VER':('经过；度过','Le bus passe à huit heures.','公交车八点经过。'),'trouver|VER':('找到；觉得','Je trouve mes clés.','我找到了钥匙。'),'parler|VER':('说话；谈论','Nous parlons français.','我们说法语。'),'falloir|VER':('需要；必须','Il faut attendre.','必须等待。'),'mettre|VER':('放；穿上','Je mets mon manteau.','我穿上外套。'),
'social|ADJ':('社会的','Le travail social est important.','社会工作很重要。'),'haut|ADJ':('高的','La montagne est haute.','这座山很高。'),'présent|ADJ':('在场的；目前的','Tous les élèves sont présents.','所有学生都到了。'),'naturel|ADJ':('自然的；天然的','C’est un produit naturel.','这是天然产品。'),'économique|ADJ':('经济的；与经济有关的','La situation économique change.','经济形势在变化。'),'entier|ADJ':('整个的；完整的','J’ai lu le livre entier.','我读完了整本书。'),'parisien|ADJ':('巴黎的','Le métro parisien est rapide.','巴黎地铁很快。'),'inquiet|ADJ':('不安的；担心的','Elle est inquiète pour son fils.','她担心儿子。'),
'cependant|ADV':('然而；不过','Il est fatigué ; cependant, il continue.','他很累，不过他继续。'),'simplement|ADV':('简单地；只是','Explique simplement la règle.','简单解释一下这个规则。'),'particulièrement|ADV':('特别；尤其','J’aime particulièrement ce film.','我特别喜欢这部电影。'),'ailleurs|ADV':('在别处；此外','Il travaille ailleurs aujourd’hui.','他今天在别处工作。'),
'point|NOM':('点；地点；位置','Le point de départ est ici.','出发点在这里。'),'corps|NOM':('身体；躯体','Le sport est bon pour le corps.','运动对身体有益。'),'doute|NOM':('怀疑；疑问','J’ai un doute.','我有点疑问。'),'loi|NOM':('法律；规律','La loi protège les citoyens.','法律保护公民。'),'fond|NOM':('底部；深处','La clé est au fond du sac.','钥匙在包底。'),'emploi|NOM':('工作；职位；就业','Elle cherche un emploi.','她在找工作。'),'développement|NOM':('发展','Le développement de la ville continue.','城市的发展仍在继续。'),'instant|NOM':('瞬间；片刻','Attends un instant.','等一下。'),
'tuer|VER':('杀死','Le poison peut tuer un animal.','毒药可能杀死一只动物。'),'agir|VER':('行动；起作用','Il faut agir vite.','必须迅速行动。'),'pousser|VER':('推；促使','Pousse la porte.','推这扇门。'),'lancer|VER':('发射；开始','Il lance le ballon.','他投出球。'),'mener|VER':('带领；进行','Elle mène le projet.','她负责这个项目。'),'déclarer|VER':('宣布；声明','Le ministre déclare la décision.','部长宣布这项决定。'),'développer|VER':('发展；使发展','La ville développe ses transports.','这座城市发展交通。'),'suffire|VER':('足够','Cela suffit pour aujourd’hui.','今天这样就够了。'),'obliger|VER':('迫使；要求','La règle oblige les élèves à attendre.','规则要求学生等待。'),'étonner|VER':('使惊讶','Cette nouvelle m’étonne.','这个消息让我惊讶。'),
'pauvre|ADJ':('贫穷的；可怜的','Cette famille est pauvre.','这个家庭很贫穷。'),'professionnel|ADJ':('专业的；职业的','Il donne un conseil professionnel.','他提供专业建议。'),'actuel|ADJ':('当前的；现在的','Le prix actuel est trop haut.','当前价格太高。'),'public|ADJ':('公共的；公开的','C’est un service public.','这是一项公共服务。'),'lors|ADV':('在……时；当时','Lors du voyage, il a plu.','旅行时下雨了。'),'que|ADV':('多么；何等','Que c’est beau !','这真美！'),
'rapport|NOM':('关系；关联','Il y a un rapport entre les deux idées.','这两个想法之间有联系。'),'regard|NOM':('目光；注视','Son regard est calme.','他的目光很平静。'),'chef|NOM':('负责人；领导；老板','Le chef parle à son équipe.','负责人和他的团队说话。'),'obtenir|VER':('获得；得到','Il obtient son diplôme.','他获得了文凭。'),'remettre|VER':('交还；递交','Je remets le document au professeur.','我把文件交给老师。'),'paraître|VER':('好像；似乎；看起来','Il paraît content.','他看起来很高兴。'),'élever|VER':('抬高；养育','Elle élève ses enfants.','她养育孩子。'),'assurer|VER':('确保；保证','Cette règle assure la sécurité.','这条规则确保安全。'),'moindre|ADJ':('较小的；最少的','Le moindre bruit le réveille.','一点声音就会叫醒他。'),'au-delà|ADV':('在更远处；超出','Le village est au-delà de la rivière.','村庄在河的另一边。'),'terme|NOM':('术语；用语；词','Ce terme est difficile.','这个术语很难。'),'antenne|NOM':('天线','L’antenne reçoit le signal.','天线接收信号。'),'constituer|VER':('构成；组成','Ces éléments constituent un groupe.','这些要素构成一个整体。')}
SOURCE_REFS={'monde|NOM':'dbnary_fr:__tr_zho_1_monde__nom__1','devoir|VER':'dbnary_fr:__tr_zho_2_devoir__verb__1','cependant|ADV':'dbnary_fr:__tr_zho_1_cependant__adv__1','point|NOM':'dbnary_fr:__tr_zho_2_point__nom__1','paraître|VER':'dbnary_fr:__tr_zho_1_paraître__verb__1','antenne|NOM':'dbnary_fr:__tr_cmn_2_antenne__nom__1'}
def build():
 facts={x['stable_lexeme_key']:x for x in json.loads(FACTS.read_text())['items']}; sel=json.loads(SEL.read_text()); items=[]
 for choice in sel['items']:
  key=choice['stable_lexeme_key']; fact=facts[key]
  if choice['selection_status']=='blocked':
   items.append({'identity':{'stable_lexeme_key':key,'runtime_lexeme_id':choice['runtime_lexeme_id'],'entry_id':None,'sense_id':None},'selection_status':'blocked','content_status':'blocked','gloss_source_strategy':'blocked','gloss_zh_short':None,'usage_note_zh':None,'relation_explanation_zh':None,'example_fr':None,'example_zh':None,'example_source_type':None,'provenance':{'authoring_surface':'Codex agent','actual_model':'unknown','generation_version':'phase2c-100-draft-v1','selection_artifact_hash':sel['artifact_hash']}}); continue
  entry,sense=choice['primary_learner_sense'].values(); gloss,fr,zh=TEXT[key]
  candidates=[c for c in fact['selected_sense_chinese_candidates'] if c['candidate_stable_ref'] in {z['candidate_stable_ref'] for z in fact['selected_sense_chinese_candidates']}]
  used=[]; strategy='ai_gap_fill'; binding=None
  if key in SOURCE_REFS:
   # Candidate provenance is retained, but source reuse never changes its structural claim.
   cand=next((c for c in candidates if c['candidate_stable_ref']==SOURCE_REFS[key]),None)
   if cand: used=[cand['candidate_stable_ref']]; strategy='sourced_reuse_external_semantic_binding' if key=='antenne|NOM' else 'sourced_reuse'
   if key=='antenne|NOM': binding='external_semantic_review; DBnary structural mapped_sense_id remains stale/misaligned'
  items.append({'identity':{'stable_lexeme_key':key,'runtime_lexeme_id':choice['runtime_lexeme_id'],'entry_id':entry,'sense_id':sense},'selection_status':'reviewed','content_status':'ai_draft','gloss_zh_short':gloss,'usage_note_zh':None,'relation_explanation_zh':None,'example_fr':fr,'example_zh':zh,'example_source_type':'ai_generated','gloss_source_strategy':strategy,'used_candidate_refs':used,'rejected_candidates':[],'provenance':{'authoring_surface':'Codex agent','actual_model':'unknown','generation_version':'phase2c-100-draft-v1','selection_artifact_hash':sel['artifact_hash'],'external_semantic_binding':binding}})
 result={'schema_version':1,'scope':'99 AI-draft learner texts bound to externally reviewed selections; one blocked record; no runtime content.','selection_artifact_hash':sel['artifact_hash'],'items':items}; result['artifact_hash']=hashlib.sha256(canon(result).encode()).hexdigest(); return result
if __name__=='__main__': OUT.write_text(json.dumps(build(),ensure_ascii=False,indent=2)+'\n')
