#!/usr/bin/env python3
"""Project reviewed Phase 2C learner aids into a minimal browser payload."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DRAFT=ROOT/'data/learner-sense-content-reviewed.json'; OUT=ROOT/'learner-sense-content.js'
def build():
 draft=json.loads(DRAFT.read_text())
 records=[]
 for item in draft['items']:
  if item['content_status']=='reviewed':
   records.append({'stable_lexeme_key':item['stable_lexeme_key'],'lexeme_id':item['runtime_lexeme_id'],'entry_id':item['entry_id'],'sense_id':item['sense_id'],'gloss_zh_short':item['gloss_zh_short'],'usage_note_zh':item['usage_note_zh'],'example_fr':item['example_fr'],'example_zh':item['example_zh'],'example_source_type':item['example_source_type'],'content_status':'reviewed','entry_rank':item['entry_rank'],'sense_number':item['sense_number']})
 return {'version':1,'scope':'Reviewed learner aid for exact Phase 2C senses; French definitions remain sourced in graph data.','records':sorted(records,key=lambda x:x['lexeme_id'])}
def serialize(payload): return '/* Generated by scripts/build_learner_sense_runtime.py. Do not edit by hand. */\nconst LEARNER_SENSE_CONTENT='+json.dumps(payload,ensure_ascii=False,separators=(',',':'))+';\n'
if __name__=='__main__': OUT.write_text(serialize(build()),encoding='utf-8')
