#!/usr/bin/env python3
"""Project the Phase 5B family-learning prototype into a minimal browser payload.

Pure packaging: no semantic prose is generated or altered here. All authored
text (explanation_zh, interaction prompts/answers, semantic_alignment) is
copied verbatim from the canonical data/phase5/family-learning-prototype.json.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/phase5/family-learning-prototype.json"
OUT = ROOT / "family-learning-prototype.js"


def build():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    families = []
    for fam in data["families"]:
        families.append({
            "familyId": fam["family_id"],
            "anchorLexemeId": fam["anchor_lexeme_id"],
            "anchorLemma": fam["anchor_lemma"],
            "anchorPos": fam["anchor_pos"],
            "totalSize": fam["total_sourced_family_size"],
            "relations": [
                {
                    "fromLexemeId": rel["from_lexeme_id"],
                    "toLexemeId": rel["to_lexeme_id"],
                    "fromLemma": rel["from_lemma"],
                    "toLemma": rel["to_lemma"],
                    "constructionSubtype": rel["construction_subtype"],
                    "morphologyLabel": rel["source_morphology_label"],
                    "alignment": rel["semantic_alignment"],
                    "explanationZh": rel["explanation_zh"],
                    "promptZh": rel["interaction_prompt_zh"],
                    "answerZh": rel["interaction_answer_zh"],
                }
                for rel in fam["teaching_relations"]
            ],
        })
    return {"version": 1, "familyCount": len(families), "families": families}


def serialize(payload):
    return ("/* Generated by scripts/build_phase5_family_runtime.py. Do not edit by hand. */\n"
            "const PHASE5_FAMILY_PROTOTYPE=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    OUT.write_text(serialize(build()), encoding="utf-8")
