#!/usr/bin/env python3
"""Normalize committed runtime review statuses after provenance model changes."""

from __future__ import annotations

import json

from runtime_graph import RUNTIME_PATH, compact_json, load_runtime


REVIEW_RANK = {
    "sourced": 5,
    "human_reviewed": 4,
    "editorial_seed": 3,
    "ai_reviewed": 2,
    "editorial_reviewed": 1,
}


def relation_key(edge: list[object]) -> tuple[object, ...]:
    return (min(edge[0], edge[1]), max(edge[0], edge[1]), edge[2], edge[3], edge[4])


def better_edge(left: list[object], right: list[object]) -> list[object]:
    left_score = (REVIEW_RANK.get(left[9], 0), left[8], bool(left[7]))
    right_score = (REVIEW_RANK.get(right[9], 0), right[8], bool(right[7]))
    return right if right_score > left_score else left


def main() -> None:
    runtime = load_runtime()
    changed = 0
    for edge in runtime["official_edges"]:
        if edge[9] == "evidence_checked":
            edge[9] = "editorial_reviewed"
            changed += 1
        if edge[7] == "AI-drafted, source-grounded, passed automated evidence checks; not independently human-reviewed.":
            edge[7] = "Editorial or AI-assisted relation accepted in the project review file; no per-edge external evidence bundle is encoded in this runtime artifact."
            changed += 1

    deduped = {}
    for edge in runtime["official_edges"]:
        key = relation_key(edge)
        if key in deduped:
            changed += 1
            deduped[key] = better_edge(deduped[key], edge)
        else:
            deduped[key] = edge
    runtime["official_edges"] = list(deduped.values())
    runtime["meta"]["official_edge_count"] = len(runtime["official_edges"])

    payload = (
        "/* Generated by scripts/export_runtime.py. Do not edit by hand. */\n"
        f"const GRAPH_META={compact_json(runtime['meta'])};\n"
        f"const GRAPH_NODES={compact_json(runtime['nodes'])};\n"
        f"const GRAPH_LINKS={compact_json(runtime['links'])};\n"
        f"const GRAPH_OFFICIAL_EDGES={compact_json(runtime['official_edges'])};\n"
        f"const GRAPH_SENSES={compact_json(runtime['senses'])};\n"
    )
    RUNTIME_PATH.write_text(payload, encoding="utf-8")
    print(json.dumps({"normalized_fields": changed}, ensure_ascii=False))


if __name__ == "__main__":
    main()
